plugins {
    id 'org.jetbrains.kotlin.jvm' version '2.0.0'
    id 'application'
}

application {
    mainClass = 'com.dionich.gofundme.payments.recurring.MainKt'
}

jar {
    manifest {
        attributes 'Main-Class': 'com.dionich.gofundme.payments.recurring.MainKt'
    }
    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

repositories {
    mavenCentral()
}

//TODO: Exclude all unnecessary dependencies.
dependencies {
    testImplementation 'org.jetbrains.kotlin:kotlin-test'
    implementation "org.jetbrains.kotlin:kotlin-stdlib"
    // https://mvnrepository.com/artifact/io.mockk/mockk
    testImplementation group: 'io.mockk', name: 'mockk', version: '1.13.13'
}

test {
    useJUnitPlatform()
}
kotlin {
    jvmToolchain(17)
}